name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Force Xcode 12
      run: xcodebuild -project 'BalinkApp.xcworkspace' -scheme 'BalinkApp' -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest' 
    - name: BalinkApp
      run: xcodebuild -project 'BalinkApp.xcworkspace' -scheme 'BalinkApp' -destination 'generic/platform=iOS' -configuration Release build CODE_SIGNING_ALLOWED=NO
